number1=7
number2=7
number3=7

# calculate sum
sum=number1+number2+number3
print("sum:",sum)

# calculate difference
difference=number1-number2-number3
print("difference:",difference)

# calculate product
product=number1*number2*number3
print("product:",product)

# calculate average
average=number1+number2+number3 /3
print("average:",average)

# area of triangle
breathe=4
height=4
area=0.5*breathe*height
print("triangle area",area)
# area of square
side=5
area=side*side
print("square area",area)
# area of circle
pi=3.14
radius=8
area=pi*radius*radius
print("circle area",area)
# area of rectangle
length=7
width=9
area=length*width
print("rectangle area",area)

